"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _team_section_photo_default from './team-section-photo-default.bones.json'
import _philosophy_team_card_360 from './philosophy-team-card-360.bones.json'
import _philosophy_team_card_432 from './philosophy-team-card-432.bones.json'
import _cases_vertical_card_360 from './cases-vertical-card-360.bones.json'
import _cases_ad_card_360 from './cases-ad-card-360.bones.json'
import _cases_vertical_card_480 from './cases-vertical-card-480.bones.json'
import _cases_ad_card_480 from './cases-ad-card-480.bones.json'
import _cases_vertical_card_768 from './cases-vertical-card-768.bones.json'
import _cases_ad_card_768 from './cases-ad-card-768.bones.json'
import _philosophy_team_card_1024 from './philosophy-team-card-1024.bones.json'
import _cases_vertical_card_1024 from './cases-vertical-card-1024.bones.json'
import _cases_ad_card_1024 from './cases-ad-card-1024.bones.json'
import _philosophy_team_card_1440 from './philosophy-team-card-1440.bones.json'
import _cases_vertical_card_1440 from './cases-vertical-card-1440.bones.json'
import _cases_ad_card_1440 from './cases-ad-card-1440.bones.json'

configureBoneyard({"color":"#ebe5df","darkColor":"#231815","animate":"shimmer","shimmerColor":"#f5f0eb","darkShimmerColor":"#342421","speed":"1.8s","transition":220})

registerBones({
  "team-section-photo-default": _team_section_photo_default,
  "philosophy-team-card-360": _philosophy_team_card_360,
  "philosophy-team-card-432": _philosophy_team_card_432,
  "cases-vertical-card-360": _cases_vertical_card_360,
  "cases-ad-card-360": _cases_ad_card_360,
  "cases-vertical-card-480": _cases_vertical_card_480,
  "cases-ad-card-480": _cases_ad_card_480,
  "cases-vertical-card-768": _cases_vertical_card_768,
  "cases-ad-card-768": _cases_ad_card_768,
  "philosophy-team-card-1024": _philosophy_team_card_1024,
  "cases-vertical-card-1024": _cases_vertical_card_1024,
  "cases-ad-card-1024": _cases_ad_card_1024,
  "philosophy-team-card-1440": _philosophy_team_card_1440,
  "cases-vertical-card-1440": _cases_vertical_card_1440,
  "cases-ad-card-1440": _cases_ad_card_1440,
})
